# Change these first
owner: nativesintech # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Natives in Tech
    url: https://nativesintech.org
  - name: Blog
    url: https://blog.nativesintech.org
  - name: Talent
    url: https://talent.nativesintech.org
  - name: Forum
    url: https://forum.nativesintech.org
  - name: Native Owned Businesses
    url: https://businesses.bynatives.app
  - name: This Land I Stand
    url: https://thislandistand.app/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/nativesintech/upptime/master/natives_in_tech.svg
  name: NiT Status
  introTitle: Status of NiT services
  introMessage: A list of NiT services and their upptime
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
